import Head from "next/head"
export default function Head() {
    return (
        <Head>
            <title>Food Recipe</title>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta
                name="description"
                content="Generated by create next app and Made with ❤️ by Ahmet Yorgancı and Hasan Böcek"
            />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
}